name: tests
on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      # - name: Lint packages
      #   run: npm run lint

      - name: Run unit tests for coverage
        run: npm run test

      - name: Add coverage comment
        uses: ArcBlock/code-coverage-assistant@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
